databases:
  - name: covidstatsproj
    databaseName: covidstatsproj
    user: covidstatsproj

services:
  - type: web
    name: covidstatsproj
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn covidstatsproj.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: covidstatsproj
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
